---
name: Build
on: push
jobs:
  app:
    name: Build Desktop App
    runs-on: ubuntu-latest
    container:
      image: ivangabriele/tauri:debian-bullseye-18
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dependencies
        run: |
          apt-get install python3-pip
          pip3 install torch  --index-url https://download.pytorch.org/whl/cpu

      - name: Run
        run: |
          export LD_LIBRARY_PATH=/usr/local/lib/python3.9/dist-packages/torch/lib
          npm run tauri -- build --verbose
        working-directory: ./semdesk-app
