---
name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  app:
    name: Build Desktop App
    runs-on: ubuntu-latest
    container:
      image: ivangabriele/tauri:debian-bullseye-18
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dependencies
        run: |
          apt-get install -y python3-pip
          pip3 install torch  --index-url https://download.pytorch.org/whl/cpu

      - name: Build Web Extension
        run: |

          npm install
          npm run dist
        working-directory: ./webext

      - name: Build Desktop App
        run: |
          export LD_LIBRARY_PATH=/usr/local/lib/python3.9/dist-packages/torch/lib
          export LIBTORCH_USE_PYTORCH=1
          export LIBTORCH_BYPASS_VERSION_CHECK=1

          npm install
          npm run tauri -- build --verbose
        working-directory: ./semtex-app

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/bundle/deb/*.deb
            target/release/bundle/appimage/*.AppImage
            webext/web-ext-artifacts/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
